name: DeliveryPerson
version: 1.0-SNAPSHOT
main: me.perplexed.delivery.Main
api-version: 1.17

commands:
  delivery:
    description: "Command for all commands!"
    permission: delivery.start
  testparticel:
    description: yes

permissions:
  delivery.start:
    description: Gives person ability to start a game
  delivery.play:
    description: Gives a person the ability to play a game. They can't start a game with this permission
